apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: frontend
  newName: ghcr.io/yuliakushnir/frontend
  newTag: latest
- name: gateway-service
  newName: ghcr.io/yuliakushnir/gateway-service
  newTag: fb5925b967e30d22513a45285fd1761966f77f56
- name: mail-service
  newName: ghcr.io/yuliakushnir/mail-service
  newTag: latest
- name: posts-service
  newName: ghcr.io/yuliakushnir/posts-service
  newTag: latest
