apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: frontend
  newName: ghcr.io/yuliakushnir/frontend
  newTag: a47283dbb1793d551cdf857c6744fbb79b9fe170
- name: gateway-service
  newName: ghcr.io/yuliakushnir/gateway-service
  newTag: 6538c7c0af41e782f6e096adab6b1a54d126d3bf
- name: mail-service
  newName: ghcr.io/yuliakushnir/mail-service
  newTag: latest
- name: posts-service
  newName: ghcr.io/yuliakushnir/posts-service
  newTag: latest
