apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: cloud-demo
  labels:
    app: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: ghcr.io/yuliakushnir/mail-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
#            - name: SPRING_RABBITMQ_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: rabbitmq-secret
#                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
#            - name: SPRING_ELASTICSEARCH_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: elasticsearch-secret
#                  key: username
#            - name: SPRING_ELASTICSEARCH_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: elasticsearch-secret
#                  key: password
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: port
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: username
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20