apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: block3-travel-blog:latest
#          imagePullPolicy: Always

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

          ports:
            - containerPort: 1000

          env:
            - name: POSTS_SERVICE_HOST
              value: "posts-service"
            - name: POSTS_SERVICE_PORT
              value: "8080"
            - name: MAIL_SERVICE_HOST
              value: "posts-service"
            - name: MAIL_SERVICE_PORT
              value: "8081"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: client-secret

#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 1000
#            initialDelaySeconds: 30
#            periodSeconds: 10
#
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 1000
#            initialDelaySeconds: 60
#            periodSeconds: 30