apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/proxy-redirect-from: "http"
#    nginx.ingress.kubernetes.io/proxy-redirect-to: "https"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/x-forwarded-prefix: ""

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # API requests go directly to the Gateway
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 1000
#            pathRewrite:
#              nginx.ingress.kubernetes.io/x-forwarded-prefix: ""
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 1000
#            pathRewrite:
#              nginx.ingress.kubernetes.io/x-forwarded-prefix: ""
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 1000
#           Everything else is Frontend (React SPA)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80