apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /default
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /secret
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 1000
#          # API requests go directly to the Gateway
#          - path: /oauth2
#            pathType: Prefix
#            backend:
#              service:
#                name: gateway-service
#                port:
#                  number: 1000
#          - path: /login
#            pathType: Prefix
#            backend:
#              service:
#                name: gateway-service
#                port:
#                  number: 1000
#          - path: /api
#            pathType: Prefix
#            backend:
#              service:
#                name: gateway-service
#                port:
#                  number: 1000
#          # Everything else is Frontend (React SPA)
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: frontend
#                port:
#                  number: 80